### PR TITLE
Fix data_by_name method signature

### PR DESCRIPTION
**Pull request by marynate**

### CODE REVIEW

**Comment by Noolarch** [comment]
The omission of the `Boolean` type is completely intentional. In Ruby everyone likes the predicate identifiers with `?` but they hate the fact that the type that you use could be something other than `Boolean` - like a `String` or a number. So in SkookumScript, types for predicates are _always_ of type `Boolean` - if you see a `?` on a variable or a method you know it will be a `Boolean`. Since this is the case, the `Boolean` is redundant so it is inferred if it is omitted.

This is indicated in the following syntax and their footnotes:
`name-predicate` - http://skookumscript.com/docs/v3.0/lang/syntax/#name-predicate
`data-definition` - http://skookumscript.com/docs/v3.0/lang/syntax/#data-definition
`parameters` and its return type - http://skookumscript.com/docs/v3.0/lang/syntax/#parameters
`param-specifier` - http://skookumscript.com/docs/v3.0/lang/syntax/#param-specifier

I know the documentation is lacking in this area. As soon as I get a chance I will put something up that explains it better. Apologies for any confusion.

**Comment by marynate** [comment]
Sometimes the predicate type is inferred as `Auto_`, so I can only make make script compiled by explicitly specify the `Boolean` type before `exist?` in `data_by_name` method:
```
ERROR: The primary return type for the last expression of the code block was expected to be
the type 'Boolean' (based on its parameters), but it is the type 'Auto_' which
is not compatible.
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  // test exist?
  !exist?
  this_code.data_by_name('a_int'; exist?)
  success:= expect_true[exist?]
>>>>>>>>>>>>>>>>>>>>>>> ------^ <<<< Line: 27, columns: 25-32
```

**Comment by Noolarch** [comment]
Thanks Nate.

It seems that this is an error parsing closures. Is `expect_true` a method that expects a closure with no arguments that has a `Boolean` return type - or is it something else?

I'll dig deeper and fix your root problem.

**Comment by marynate** [comment]
Yes, `expect_true` is a method expecting a closure which has `Boolean` as return type:
```
( () Boolean code) Boolean
```

**Pull request closed without merging**
